name: cms_flutter
description: 'A mobile app for the app.100xDevs.com'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.3.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
